"""Constants verified against the Kitsas source and against real books."""

TILA_POISTETTU = 0
TILA_MALLIPOHJA = 5
TILA_HYLATTY = 10
TILA_SAAPUNUT = 20
TILA_TARKASTETTU = 30
TILA_HYVAKSYTTY = 40
TILA_LUONNOS = 50
TILA_KIRJANPIDOSSA = 100

TOSITE_MENO = 100

VIENTI_OSTO_KIRJAUS = 101
VIENTI_OSTO_VASTAKIRJAUS = 102

TILITYYPPI_PANKKI = "ARP"
TILITYYPPI_OSTOVELAT = "BO"

SUPPORTED_KPVERSIO = {24}
